plugins { id 'com.android.application' }

android {
    namespace 'com.morteza.aria'
    compileSdk 35

    defaultConfig {
        applicationId 'com.morteza.aria'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.0.4'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packaging {
        resources {
            excludes += ['/META-INF/AL2.0', '/META-INF/LGPL2.1']
        }
    }
}

dependencies {
    implementation 'net.java.dev.jna:jna:5.18.1@aar'
    implementation 'com.alphacephei:vosk-android:0.3.75@aar'
}
